.. list-table::
    :header-rows: 1
    :widths: 30 12 12 15 15 15

    * - Language
      - Django code
      - Locale
      - Google (free)
      - Google Cloud
      - Amazon
    * - Afrikaans
      - ``af``
      - ``af``
      - ``af``
      - ``af``
      - ``af``
    * - Arabic
      - ``ar``
      - ``ar``
      - ``ar``
      - ``ar``
      - ``ar``
    * - Algerian Arabic
      - ``ar-dz``
      - ``ar_DZ``
      - ``ar``
      - ``ar``
      - ``ar``
    * - Asturian
      - ``ast``
      - ``ast``
      - —
      - —
      - —
    * - Azerbaijani
      - ``az``
      - ``az``
      - ``az``
      - ``az``
      - ``az``
    * - Bulgarian
      - ``bg``
      - ``bg``
      - ``bg``
      - ``bg``
      - ``bg``
    * - Belarusian
      - ``be``
      - ``be``
      - ``be``
      - ``be``
      - —
    * - Bengali
      - ``bn``
      - ``bn``
      - ``bn``
      - ``bn``
      - ``bn``
    * - Breton
      - ``br``
      - ``br``
      - —
      - ``br``
      - —
    * - Bosnian
      - ``bs``
      - ``bs``
      - ``bs``
      - ``bs``
      - ``bs``
    * - Catalan
      - ``ca``
      - ``ca``
      - ``ca``
      - ``ca``
      - ``ca``
    * - Central Kurdish (Sorani)
      - ``ckb``
      - ``ckb``
      - ``ckb``
      - ``ckb``
      - —
    * - Czech
      - ``cs``
      - ``cs``
      - ``cs``
      - ``cs``
      - ``cs``
    * - Welsh
      - ``cy``
      - ``cy``
      - ``cy``
      - ``cy``
      - ``cy``
    * - Danish
      - ``da``
      - ``da``
      - ``da``
      - ``da``
      - ``da``
    * - German
      - ``de``
      - ``de``
      - ``de``
      - ``de``
      - ``de``
    * - Lower Sorbian
      - ``dsb``
      - ``dsb``
      - —
      - —
      - —
    * - Greek
      - ``el``
      - ``el``
      - ``el``
      - ``el``
      - ``el``
    * - Esperanto
      - ``eo``
      - ``eo``
      - ``eo``
      - ``eo``
      - —
    * - Spanish
      - ``es``
      - ``es``
      - ``es``
      - ``es``
      - ``es``
    * - Argentinian Spanish
      - ``es-ar``
      - ``es_AR``
      - ``es``
      - ``es``
      - ``es-MX``
    * - Colombian Spanish
      - ``es-co``
      - ``es_CO``
      - ``es``
      - ``es``
      - ``es-MX``
    * - Mexican Spanish
      - ``es-mx``
      - ``es_MX``
      - ``es``
      - ``es``
      - ``es-MX``
    * - Nicaraguan Spanish
      - ``es-ni``
      - ``es_NI``
      - ``es``
      - ``es``
      - ``es-MX``
    * - Venezuelan Spanish
      - ``es-ve``
      - ``es_VE``
      - ``es``
      - ``es``
      - ``es-MX``
    * - Estonian
      - ``et``
      - ``et``
      - ``et``
      - ``et``
      - ``et``
    * - Basque
      - ``eu``
      - ``eu``
      - ``eu``
      - ``eu``
      - —
    * - Persian
      - ``fa``
      - ``fa``
      - ``fa``
      - ``fa``
      - ``fa``
    * - Finnish
      - ``fi``
      - ``fi``
      - ``fi``
      - ``fi``
      - ``fi``
    * - French
      - ``fr``
      - ``fr``
      - ``fr``
      - ``fr``
      - ``fr``
    * - Frisian
      - ``fy``
      - ``fy``
      - ``fy``
      - ``fy``
      - —
    * - Irish
      - ``ga``
      - ``ga``
      - ``ga``
      - ``ga``
      - ``ga``
    * - Scottish Gaelic
      - ``gd``
      - ``gd``
      - ``gd``
      - ``gd``
      - —
    * - Galician
      - ``gl``
      - ``gl``
      - ``gl``
      - ``gl``
      - —
    * - Hebrew
      - ``he``
      - ``he``
      - ``he``
      - ``he``
      - ``he``
    * - Hindi
      - ``hi``
      - ``hi``
      - ``hi``
      - ``hi``
      - ``hi``
    * - Croatian
      - ``hr``
      - ``hr``
      - ``hr``
      - ``hr``
      - ``hr``
    * - Upper Sorbian
      - ``hsb``
      - ``hsb``
      - —
      - —
      - —
    * - Haitian Creole
      - ``ht``
      - ``ht``
      - ``ht``
      - ``ht``
      - ``ht``
    * - Hungarian
      - ``hu``
      - ``hu``
      - ``hu``
      - ``hu``
      - ``hu``
    * - Armenian
      - ``hy``
      - ``hy``
      - ``hy``
      - ``hy``
      - ``hy``
    * - Interlingua
      - ``ia``
      - ``ia``
      - —
      - —
      - —
    * - Indonesian
      - ``id``
      - ``id``
      - ``id``
      - ``id``
      - ``id``
    * - Igbo
      - ``ig``
      - ``ig``
      - ``ig``
      - ``ig``
      - —
    * - Ido
      - ``io``
      - ``io``
      - —
      - —
      - —
    * - Icelandic
      - ``is``
      - ``is``
      - ``is``
      - ``is``
      - ``is``
    * - Italian
      - ``it``
      - ``it``
      - ``it``
      - ``it``
      - ``it``
    * - Japanese
      - ``ja``
      - ``ja``
      - ``ja``
      - ``ja``
      - ``ja``
    * - Georgian
      - ``ka``
      - ``ka``
      - ``ka``
      - ``ka``
      - ``ka``
    * - Kabyle
      - ``kab``
      - ``kab``
      - —
      - —
      - —
    * - Kazakh
      - ``kk``
      - ``kk``
      - ``kk``
      - ``kk``
      - ``kk``
    * - Khmer
      - ``km``
      - ``km``
      - ``km``
      - ``km``
      - —
    * - Kannada
      - ``kn``
      - ``kn``
      - ``kn``
      - ``kn``
      - ``kn``
    * - Korean
      - ``ko``
      - ``ko``
      - ``ko``
      - ``ko``
      - ``ko``
    * - Kyrgyz
      - ``ky``
      - ``ky``
      - ``ky``
      - ``ky``
      - —
    * - Luxembourgish
      - ``lb``
      - ``lb``
      - ``lb``
      - ``lb``
      - —
    * - Lithuanian
      - ``lt``
      - ``lt``
      - ``lt``
      - ``lt``
      - ``lt``
    * - Latvian
      - ``lv``
      - ``lv``
      - ``lv``
      - ``lv``
      - ``lv``
    * - Macedonian
      - ``mk``
      - ``mk``
      - ``mk``
      - ``mk``
      - ``mk``
    * - Malayalam
      - ``ml``
      - ``ml``
      - ``ml``
      - ``ml``
      - ``ml``
    * - Mongolian
      - ``mn``
      - ``mn``
      - ``mn``
      - ``mn``
      - ``mn``
    * - Marathi
      - ``mr``
      - ``mr``
      - ``mr``
      - ``mr``
      - ``mr``
    * - Malay
      - ``ms``
      - ``ms``
      - ``ms``
      - ``ms``
      - ``ms``
    * - Burmese
      - ``my``
      - ``my``
      - ``my``
      - ``my``
      - —
    * - Norwegian Bokmål
      - ``nb``
      - ``nb``
      - ``no``
      - ``no``
      - ``no``
    * - Nepali
      - ``ne``
      - ``ne``
      - ``ne``
      - ``ne``
      - —
    * - Dutch
      - ``nl``
      - ``nl``
      - ``nl``
      - ``nl``
      - ``nl``
    * - Norwegian Nynorsk
      - ``nn``
      - ``nn``
      - —
      - —
      - —
    * - Ossetic
      - ``os``
      - ``os``
      - —
      - —
      - —
    * - Punjabi
      - ``pa``
      - ``pa``
      - ``pa``
      - ``pa``
      - ``pa``
    * - Polish
      - ``pl``
      - ``pl``
      - ``pl``
      - ``pl``
      - ``pl``
    * - Portuguese
      - ``pt``
      - ``pt``
      - ``pt``
      - ``pt-PT``
      - ``pt-PT``
    * - Brazilian Portuguese
      - ``pt-br``
      - ``pt_BR``
      - ``pt``
      - ``pt``
      - ``pt``
    * - Romanian
      - ``ro``
      - ``ro``
      - ``ro``
      - ``ro``
      - ``ro``
    * - Russian
      - ``ru``
      - ``ru``
      - ``ru``
      - ``ru``
      - ``ru``
    * - Slovak
      - ``sk``
      - ``sk``
      - ``sk``
      - ``sk``
      - ``sk``
    * - Slovenian
      - ``sl``
      - ``sl``
      - ``sl``
      - ``sl``
      - ``sl``
    * - Albanian
      - ``sq``
      - ``sq``
      - ``sq``
      - ``sq``
      - ``sq``
    * - Serbian
      - ``sr``
      - ``sr``
      - ``sr``
      - ``sr``
      - —
    * - Serbian Latin
      - ``sr-latn``
      - ``sr_Latn``
      - —
      - —
      - ``sr``
    * - Swedish
      - ``sv``
      - ``sv``
      - ``sv``
      - ``sv``
      - ``sv``
    * - Swahili
      - ``sw``
      - ``sw``
      - ``sw``
      - ``sw``
      - ``sw``
    * - Tamil
      - ``ta``
      - ``ta``
      - ``ta``
      - ``ta``
      - ``ta``
    * - Telugu
      - ``te``
      - ``te``
      - ``te``
      - ``te``
      - ``te``
    * - Tajik
      - ``tg``
      - ``tg``
      - ``tg``
      - ``tg``
      - —
    * - Thai
      - ``th``
      - ``th``
      - ``th``
      - ``th``
      - ``th``
    * - Turkmen
      - ``tk``
      - ``tk``
      - ``tk``
      - ``tk``
      - —
    * - Turkish
      - ``tr``
      - ``tr``
      - ``tr``
      - ``tr``
      - ``tr``
    * - Tatar
      - ``tt``
      - ``tt``
      - ``tt``
      - ``tt``
      - —
    * - Udmurt
      - ``udm``
      - ``udm``
      - ``udm``
      - —
      - —
    * - Uyghur
      - ``ug``
      - ``ug``
      - ``ug``
      - ``ug``
      - —
    * - Ukrainian
      - ``uk``
      - ``uk``
      - ``uk``
      - ``uk``
      - ``uk``
    * - Urdu
      - ``ur``
      - ``ur``
      - ``ur``
      - ``ur``
      - ``ur``
    * - Uzbek
      - ``uz``
      - ``uz``
      - ``uz``
      - ``uz``
      - ``uz``
    * - Vietnamese
      - ``vi``
      - ``vi``
      - ``vi``
      - ``vi``
      - ``vi``
    * - Simplified Chinese
      - ``zh-hans``
      - ``zh_Hans``
      - ``zh-cn``
      - ``zh-CN``
      - ``zh``
    * - Traditional Chinese
      - ``zh-hant``
      - ``zh_Hant``
      - ``zh-tw``
      - ``zh-TW``
      - ``zh-TW``
